/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './thongthan.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '@angular/forms/src/directives/default_value_accessor';
import * as import11 from '@angular/forms/src/directives/ng_model';
import * as import12 from '@angular/forms/src/directives/ng_control_status';
import * as import13 from './dropdown.component';
import * as import14 from '../upload/upload.component';
import * as import15 from '@angular/core/src/linker/element_ref';
import * as import16 from './dropdown.component.ngfactory';
import * as import17 from './thongthan.service';
import * as import18 from '../upload/upload.component.ngfactory';
import * as import19 from '@angular/forms/src/directives/control_value_accessor';
import * as import20 from '@angular/forms/src/directives/ng_control';
var renderType_ThongthanComponent_Host:import0.RenderComponentType = (null as any);
class _View_ThongthanComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ThongthanComponent_0_4:import3.ThongthanComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ThongthanComponent_Host0,renderType_ThongthanComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-dropdown',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ThongthanComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ThongthanComponent_0_4 = new import3.ThongthanComponent();
    this._appEl_0.initComponent(this._ThongthanComponent_0_4,[],compView_0);
    compView_0.create(this._ThongthanComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ThongthanComponent) && (0 === requestNodeIndex))) { return this._ThongthanComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_ThongthanComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ThongthanComponent_Host === (null as any))) { (renderType_ThongthanComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,[],{})); }
  return new _View_ThongthanComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ThongthanComponentNgFactory:import9.ComponentFactory<import3.ThongthanComponent> = new import9.ComponentFactory<import3.ThongthanComponent>('app-dropdown',viewFactory_ThongthanComponent_Host0,import3.ThongthanComponent);
const styles_ThongthanComponent:any[] = [];
var renderType_ThongthanComponent:import0.RenderComponentType = (null as any);
class _View_ThongthanComponent0 extends import1.AppView<import3.ThongthanComponent> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _DefaultValueAccessor_13_3:import10.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_13_4:any[];
  _NgModel_13_5:import11.NgModel;
  _NgControl_13_6:any;
  _NgControlStatus_13_7:import12.NgControlStatus;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _el_24:any;
  /*private*/ _appEl_24:import2.AppElement;
  _AMSDropdownComponent_24_4:import13.AMSDropdownComponent;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  /*private*/ _appEl_32:import2.AppElement;
  _uploadComponent_32_4:import14.uploadComponent;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ThongthanComponent0,renderType_ThongthanComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'h1',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'คิดคูปองพนักงาน',(null as any));
    this._text_2 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_3 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','row');
    this._text_4 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_3,'div',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','col-md-6');
    this._text_6 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'h4',(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'Date',(null as any));
    this._text_9 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._text_10 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_3,'div',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','col-md-6');
    this._text_12 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'input',(null as any));
    this.renderer.setElementAttribute(this._el_13,'type','date');
    this._DefaultValueAccessor_13_3 = new import10.DefaultValueAccessor(this.renderer,new import15.ElementRef(this._el_13));
    this._NG_VALUE_ACCESSOR_13_4 = [this._DefaultValueAccessor_13_3];
    this._NgModel_13_5 = new import11.NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_13_4);
    this._NgControl_13_6 = this._NgModel_13_5;
    this._NgControlStatus_13_7 = new import12.NgControlStatus(this._NgControl_13_6);
    this._text_14 = this.renderer.createText(this._el_11,'\n    ',(null as any));
    this._text_15 = this.renderer.createText(this._el_3,'\n',(null as any));
    this._text_16 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_17 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_17,'class','row');
    this._text_18 = this.renderer.createText(this._el_17,'\n    ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_17,'div',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','col-md-6');
    this._el_20 = this.renderer.createElement(this._el_19,'h4',(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'Choose Branch: ',(null as any));
    this._text_22 = this.renderer.createText(this._el_17,'\n    ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_17,'div',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','col-md-6');
    this._el_24 = this.renderer.createElement(this._el_23,'app-ams-dropdown',(null as any));
    this._appEl_24 = new import2.AppElement(24,23,this,this._el_24);
    var compView_24:any = import16.viewFactory_AMSDropdownComponent0(this.viewUtils,this.injector(24),this._appEl_24);
    this._AMSDropdownComponent_24_4 = new import13.AMSDropdownComponent(this.parentInjector.get(import17.ThongthanService));
    this._appEl_24.initComponent(this._AMSDropdownComponent_24_4,[],compView_24);
    compView_24.create(this._AMSDropdownComponent_24_4,[],(null as any));
    this._text_25 = this.renderer.createText(this._el_17,'\n',(null as any));
    this._text_26 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_27 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._el_28 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._text_29 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_30 = this.renderer.createElement(parentRenderNode,'hr',(null as any));
    this._text_31 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_32 = this.renderer.createElement(parentRenderNode,'app-upload',(null as any));
    this._appEl_32 = new import2.AppElement(32,(null as any),this,this._el_32);
    var compView_32:any = import18.viewFactory_uploadComponent0(this.viewUtils,this.injector(32),this._appEl_32);
    this._uploadComponent_32_4 = new import14.uploadComponent();
    this._appEl_32.initComponent(this._uploadComponent_32_4,[],compView_32);
    compView_32.create(this._uploadComponent_32_4,[],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_13,'ngModelChange',this.eventHandler(this._handle_ngModelChange_13_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_13,'input',this.eventHandler(this._handle_input_13_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_13,'blur',this.eventHandler(this._handle_blur_13_2.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    const subscription_0:any = this._NgModel_13_5.update.subscribe(this.eventHandler(this._handle_ngModelChange_13_0.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import10.DefaultValueAccessor) && (13 === requestNodeIndex))) { return this._DefaultValueAccessor_13_3; }
    if (((token === import19.NG_VALUE_ACCESSOR) && (13 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_13_4; }
    if (((token === import11.NgModel) && (13 === requestNodeIndex))) { return this._NgModel_13_5; }
    if (((token === import20.NgControl) && (13 === requestNodeIndex))) { return this._NgControl_13_6; }
    if (((token === import12.NgControlStatus) && (13 === requestNodeIndex))) { return this._NgControlStatus_13_7; }
    if (((token === import13.AMSDropdownComponent) && (24 === requestNodeIndex))) { return this._AMSDropdownComponent_24_4; }
    if (((token === import14.uploadComponent) && (32 === requestNodeIndex))) { return this._uploadComponent_32_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_4:any = this.context.date;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgModel_13_5.model = currVal_4;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_4,currVal_4);
      this._expr_4 = currVal_4;
    }
    if ((changes !== (null as any))) { this._NgModel_13_5.ngOnChanges(changes); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._AMSDropdownComponent_24_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_5:any = this._NgControlStatus_13_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_13,'ng-untouched',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatus_13_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_13,'ng-touched',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatus_13_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_13,'ng-pristine',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatus_13_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_13,'ng-dirty',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatus_13_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_13,'ng-valid',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatus_13_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_13,'ng-invalid',currVal_10);
      this._expr_10 = currVal_10;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_13_5.ngOnDestroy();
  }
  private _handle_ngModelChange_13_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.date = $event)) !== false);
    const pd_1:any = ((<any>this.context.printDate()) !== false);
    return ((true && pd_0) && pd_1);
  }
  private _handle_input_13_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_13_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_13_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_13_3.onTouched()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_ThongthanComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ThongthanComponent> {
  if ((renderType_ThongthanComponent === (null as any))) { (renderType_ThongthanComponent = viewUtils.createRenderComponentType('C:/Users/chana/Desktop/Thongthan Project/07 Errors/assets/app/thongthan/thongthan.component.html',0,import8.ViewEncapsulation.None,styles_ThongthanComponent,{})); }
  return new _View_ThongthanComponent0(viewUtils,parentInjector,declarationEl);
}