/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './thongthan.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '../upload/upload.module';
import * as import4 from 'ng2-file-upload/file-upload/file-upload.module';
import * as import5 from '@angular/forms/src/directives';
import * as import6 from '@angular/forms/src/form_providers';
import * as import7 from 'angular2-multiselect-dropdown/src/app/angular2-multiselect-dropdown/multiselect.component';
import * as import8 from '@angular/common/src/localization';
import * as import9 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import10 from '@angular/core/src/di/injector';
import * as import11 from '@angular/core/src/i18n/tokens';
class ThongthanModuleInjector extends import0.NgModuleInjector<import1.ThongthanModule> {
  _CommonModule_0:import2.CommonModule;
  _FUModule_1:import3.FUModule;
  _FileUploadModule_2:import4.FileUploadModule;
  _InternalFormsSharedModule_3:import5.InternalFormsSharedModule;
  _FormsModule_4:import6.FormsModule;
  _AngularMultiSelectModule_5:import7.AngularMultiSelectModule;
  _ThongthanModule_6:import1.ThongthanModule;
  __NgLocalization_7:import8.NgLocaleLocalization;
  __RadioControlRegistry_8:import9.RadioControlRegistry;
  constructor(parent:import10.Injector) {
    super(parent,[],[]);
  }
  get _NgLocalization_7():import8.NgLocaleLocalization {
    if ((this.__NgLocalization_7 == (null as any))) { (this.__NgLocalization_7 = new import8.NgLocaleLocalization(this.parent.get(import11.LOCALE_ID))); }
    return this.__NgLocalization_7;
  }
  get _RadioControlRegistry_8():import9.RadioControlRegistry {
    if ((this.__RadioControlRegistry_8 == (null as any))) { (this.__RadioControlRegistry_8 = new import9.RadioControlRegistry()); }
    return this.__RadioControlRegistry_8;
  }
  createInternal():import1.ThongthanModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._FUModule_1 = new import3.FUModule();
    this._FileUploadModule_2 = new import4.FileUploadModule();
    this._InternalFormsSharedModule_3 = new import5.InternalFormsSharedModule();
    this._FormsModule_4 = new import6.FormsModule();
    this._AngularMultiSelectModule_5 = new import7.AngularMultiSelectModule();
    this._ThongthanModule_6 = new import1.ThongthanModule();
    return this._ThongthanModule_6;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.FUModule)) { return this._FUModule_1; }
    if ((token === import4.FileUploadModule)) { return this._FileUploadModule_2; }
    if ((token === import5.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_3; }
    if ((token === import6.FormsModule)) { return this._FormsModule_4; }
    if ((token === import7.AngularMultiSelectModule)) { return this._AngularMultiSelectModule_5; }
    if ((token === import1.ThongthanModule)) { return this._ThongthanModule_6; }
    if ((token === import8.NgLocalization)) { return this._NgLocalization_7; }
    if ((token === import9.RadioControlRegistry)) { return this._RadioControlRegistry_8; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const ThongthanModuleNgFactory:import0.NgModuleFactory<import1.ThongthanModule> = new import0.NgModuleFactory(ThongthanModuleInjector,import1.ThongthanModule);