/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './upload.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from 'ng2-file-upload/file-upload/file-select.directive';
import * as import11 from '@angular/common/src/directives/ng_for';
import * as import12 from '@angular/common/src/directives/ng_style';
import * as import13 from '@angular/common/src/pipes/number_pipe';
import * as import14 from '@angular/core/src/linker/element_ref';
import * as import15 from '@angular/core/src/linker/template_ref';
import * as import16 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import17 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import18 from '@angular/core/src/i18n/tokens';
import * as import19 from '@angular/common/src/directives/ng_if';
var renderType_uploadComponent_Host:import0.RenderComponentType = (null as any);
class _View_uploadComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _uploadComponent_0_4:import3.uploadComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_uploadComponent_Host0,renderType_uploadComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-upload',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_uploadComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._uploadComponent_0_4 = new import3.uploadComponent();
    this._appEl_0.initComponent(this._uploadComponent_0_4,[],compView_0);
    compView_0.create(this._uploadComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.uploadComponent) && (0 === requestNodeIndex))) { return this._uploadComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_uploadComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_uploadComponent_Host === (null as any))) { (renderType_uploadComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,[],{})); }
  return new _View_uploadComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const uploadComponentNgFactory:import9.ComponentFactory<import3.uploadComponent> = new import9.ComponentFactory<import3.uploadComponent>('app-upload',viewFactory_uploadComponent_Host0,import3.uploadComponent);
const styles_uploadComponent:any[] = ['.my-drop-zone[_ngcontent-%COMP%] { border: dotted 3px lightgray; }\n    .nv-file-over[_ngcontent-%COMP%] { border: dotted 3px red; } \n    .another-file-over-class[_ngcontent-%COMP%] { border: dotted 3px green; }\n\n    html[_ngcontent-%COMP%], body[_ngcontent-%COMP%] { height: 100%; }'];
var renderType_uploadComponent:import0.RenderComponentType = (null as any);
class _View_uploadComponent0 extends import1.AppView<import3.uploadComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _FileSelectDirective_38_3:import10.FileSelectDirective;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  _text_47:any;
  _text_48:any;
  _el_49:any;
  _text_50:any;
  _el_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _el_55:any;
  _text_56:any;
  _text_57:any;
  _el_58:any;
  _text_59:any;
  _text_60:any;
  _el_61:any;
  _text_62:any;
  _text_63:any;
  _el_64:any;
  _text_65:any;
  _text_66:any;
  _el_67:any;
  _text_68:any;
  _text_69:any;
  _text_70:any;
  _text_71:any;
  _el_72:any;
  _text_73:any;
  _anchor_74:any;
  /*private*/ _appEl_74:import2.AppElement;
  _TemplateRef_74_5:any;
  _NgFor_74_6:import11.NgFor;
  _text_75:any;
  _text_76:any;
  _text_77:any;
  _el_78:any;
  _text_79:any;
  _el_80:any;
  _text_81:any;
  _el_82:any;
  _text_83:any;
  _el_84:any;
  _NgStyle_84_3:import12.NgStyle;
  _text_85:any;
  _text_86:any;
  _text_87:any;
  _el_88:any;
  _text_89:any;
  _el_90:any;
  _text_91:any;
  _text_92:any;
  _el_93:any;
  _text_94:any;
  _el_95:any;
  _text_96:any;
  _text_97:any;
  _el_98:any;
  _text_99:any;
  _el_100:any;
  _text_101:any;
  _text_102:any;
  _text_103:any;
  _text_104:any;
  _text_105:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  _pipe_number_0:import13.DecimalPipe;
  _map_0:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_10:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_uploadComponent0,renderType_uploadComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_1,'class','container');
    this._text_2 = this.renderer.createText(this._el_1,'\n\n    ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'div',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','navbar navbar-default');
    this._text_4 = this.renderer.createText(this._el_3,'\n        ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_3,'div',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','navbar-header');
    this._text_6 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'a',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','navbar-brand');
    this.renderer.setElementAttribute(this._el_7,'href','./thongthan');
    this._text_8 = this.renderer.createText(this._el_7,'Thongthan Stock Data Upload',(null as any));
    this._text_9 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._text_10 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._text_11 = this.renderer.createText(this._el_1,'\n\n    ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_1,'div',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','row');
    this._text_13 = this.renderer.createText(this._el_12,'\n\n        ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_12,'div',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','col-md-3');
    this._text_15 = this.renderer.createText(this._el_14,'\n\n            ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_14,'h3',(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'Select files',(null as any));
    this._text_18 = this.renderer.createText(this._el_14,'\n\n            ',(null as any));
    this._text_19 = this.renderer.createText(this._el_14,'\n                 ',(null as any));
    this._text_20 = this.renderer.createText(this._el_14,'\n                 ',(null as any));
    this._text_21 = this.renderer.createText(this._el_14,'\n                 ',(null as any));
    this._text_22 = this.renderer.createText(this._el_14,'\n                 ',(null as any));
    this._text_23 = this.renderer.createText(this._el_14,'\n                ',(null as any));
    this._text_24 = this.renderer.createText(this._el_14,'\n            ',(null as any));
    this._text_25 = this.renderer.createText(this._el_14,'\n\n            ',(null as any));
    this._text_26 = this.renderer.createText(this._el_14,'\n                 ',(null as any));
    this._text_27 = this.renderer.createText(this._el_14,'\n                 ',(null as any));
    this._text_28 = this.renderer.createText(this._el_14,'\n                 ',(null as any));
    this._text_29 = this.renderer.createText(this._el_14,'\n                 ',(null as any));
    this._text_30 = this.renderer.createText(this._el_14,'\n                ',(null as any));
    this._text_31 = this.renderer.createText(this._el_14,'\n            ',(null as any));
    this._text_32 = this.renderer.createText(this._el_14,'\n\n            ',(null as any));
    this._text_33 = this.renderer.createText(this._el_14,'\n            ',(null as any));
    this._text_34 = this.renderer.createText(this._el_14,'\n            ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_14,'hr',(null as any));
    this._text_36 = this.renderer.createText(this._el_14,'\n            ',(null as any));
    this._text_37 = this.renderer.createText(this._el_14,'\n            ',(null as any));
    this._el_38 = this.renderer.createElement(this._el_14,'input',(null as any));
    this.renderer.setElementAttribute(this._el_38,'ng2FileSelect','');
    this.renderer.setElementAttribute(this._el_38,'type','file');
    this._FileSelectDirective_38_3 = new import10.FileSelectDirective(new import14.ElementRef(this._el_38));
    this._text_39 = this.renderer.createText(this._el_14,'\n        ',(null as any));
    this._text_40 = this.renderer.createText(this._el_12,'\n\n        ',(null as any));
    this._el_41 = this.renderer.createElement(this._el_12,'div',(null as any));
    this.renderer.setElementAttribute(this._el_41,'class','col-md-9');
    this.renderer.setElementAttribute(this._el_41,'style','margin-bottom: 40px');
    this._text_42 = this.renderer.createText(this._el_41,'\n\n            ',(null as any));
    this._el_43 = this.renderer.createElement(this._el_41,'h3',(null as any));
    this._text_44 = this.renderer.createText(this._el_43,'Upload queue',(null as any));
    this._text_45 = this.renderer.createText(this._el_41,'\n            ',(null as any));
    this._el_46 = this.renderer.createElement(this._el_41,'p',(null as any));
    this._text_47 = this.renderer.createText(this._el_46,'',(null as any));
    this._text_48 = this.renderer.createText(this._el_41,'\n\n            ',(null as any));
    this._el_49 = this.renderer.createElement(this._el_41,'table',(null as any));
    this.renderer.setElementAttribute(this._el_49,'class','table');
    this._text_50 = this.renderer.createText(this._el_49,'\n                ',(null as any));
    this._el_51 = this.renderer.createElement(this._el_49,'thead',(null as any));
    this._text_52 = this.renderer.createText(this._el_51,'\n                ',(null as any));
    this._el_53 = this.renderer.createElement(this._el_51,'tr',(null as any));
    this._text_54 = this.renderer.createText(this._el_53,'\n                    ',(null as any));
    this._el_55 = this.renderer.createElement(this._el_53,'th',(null as any));
    this.renderer.setElementAttribute(this._el_55,'width','50%');
    this._text_56 = this.renderer.createText(this._el_55,'Name',(null as any));
    this._text_57 = this.renderer.createText(this._el_53,'\n                    ',(null as any));
    this._el_58 = this.renderer.createElement(this._el_53,'th',(null as any));
    this._text_59 = this.renderer.createText(this._el_58,'Size',(null as any));
    this._text_60 = this.renderer.createText(this._el_53,'\n                    ',(null as any));
    this._el_61 = this.renderer.createElement(this._el_53,'th',(null as any));
    this._text_62 = this.renderer.createText(this._el_61,'Progress',(null as any));
    this._text_63 = this.renderer.createText(this._el_53,'\n                    ',(null as any));
    this._el_64 = this.renderer.createElement(this._el_53,'th',(null as any));
    this._text_65 = this.renderer.createText(this._el_64,'Status',(null as any));
    this._text_66 = this.renderer.createText(this._el_53,'\n                    ',(null as any));
    this._el_67 = this.renderer.createElement(this._el_53,'th',(null as any));
    this._text_68 = this.renderer.createText(this._el_67,'Actions',(null as any));
    this._text_69 = this.renderer.createText(this._el_53,'\n                ',(null as any));
    this._text_70 = this.renderer.createText(this._el_51,'\n                ',(null as any));
    this._text_71 = this.renderer.createText(this._el_49,'\n                ',(null as any));
    this._el_72 = this.renderer.createElement(this._el_49,'tbody',(null as any));
    this._text_73 = this.renderer.createText(this._el_72,'\n                ',(null as any));
    this._anchor_74 = this.renderer.createTemplateAnchor(this._el_72,(null as any));
    this._appEl_74 = new import2.AppElement(74,72,this,this._anchor_74);
    this._TemplateRef_74_5 = new import15.TemplateRef_(this._appEl_74,viewFactory_uploadComponent1);
    this._NgFor_74_6 = new import11.NgFor(this._appEl_74.vcRef,this._TemplateRef_74_5,this.parentInjector.get(import16.IterableDiffers),this.ref);
    this._text_75 = this.renderer.createText(this._el_72,'\n                ',(null as any));
    this._text_76 = this.renderer.createText(this._el_49,'\n            ',(null as any));
    this._text_77 = this.renderer.createText(this._el_41,'\n\n            ',(null as any));
    this._el_78 = this.renderer.createElement(this._el_41,'div',(null as any));
    this._text_79 = this.renderer.createText(this._el_78,'\n                ',(null as any));
    this._el_80 = this.renderer.createElement(this._el_78,'div',(null as any));
    this._text_81 = this.renderer.createText(this._el_80,'\n                    Queue progress:\n                    ',(null as any));
    this._el_82 = this.renderer.createElement(this._el_80,'div',(null as any));
    this.renderer.setElementAttribute(this._el_82,'class','progress');
    this.renderer.setElementAttribute(this._el_82,'style','');
    this._text_83 = this.renderer.createText(this._el_82,'\n                        ',(null as any));
    this._el_84 = this.renderer.createElement(this._el_82,'div',(null as any));
    this.renderer.setElementAttribute(this._el_84,'class','progress-bar');
    this.renderer.setElementAttribute(this._el_84,'role','progressbar');
    this._NgStyle_84_3 = new import12.NgStyle(this.parentInjector.get(import17.KeyValueDiffers),new import14.ElementRef(this._el_84),this.renderer);
    this._text_85 = this.renderer.createText(this._el_82,'\n                    ',(null as any));
    this._text_86 = this.renderer.createText(this._el_80,'\n                ',(null as any));
    this._text_87 = this.renderer.createText(this._el_78,'\n                ',(null as any));
    this._el_88 = this.renderer.createElement(this._el_78,'button',(null as any));
    this.renderer.setElementAttribute(this._el_88,'class','btn btn-success btn-s');
    this.renderer.setElementAttribute(this._el_88,'type','button');
    this._text_89 = this.renderer.createText(this._el_88,'\n                    ',(null as any));
    this._el_90 = this.renderer.createElement(this._el_88,'span',(null as any));
    this.renderer.setElementAttribute(this._el_90,'class','glyphicon glyphicon-upload');
    this._text_91 = this.renderer.createText(this._el_88,' Upload all\n                ',(null as any));
    this._text_92 = this.renderer.createText(this._el_78,'\n                ',(null as any));
    this._el_93 = this.renderer.createElement(this._el_78,'button',(null as any));
    this.renderer.setElementAttribute(this._el_93,'class','btn btn-warning btn-s');
    this.renderer.setElementAttribute(this._el_93,'type','button');
    this._text_94 = this.renderer.createText(this._el_93,'\n                    ',(null as any));
    this._el_95 = this.renderer.createElement(this._el_93,'span',(null as any));
    this.renderer.setElementAttribute(this._el_95,'class','glyphicon glyphicon-ban-circle');
    this._text_96 = this.renderer.createText(this._el_93,' Cancel all\n                ',(null as any));
    this._text_97 = this.renderer.createText(this._el_78,'\n                ',(null as any));
    this._el_98 = this.renderer.createElement(this._el_78,'button',(null as any));
    this.renderer.setElementAttribute(this._el_98,'class','btn btn-danger btn-s');
    this.renderer.setElementAttribute(this._el_98,'type','button');
    this._text_99 = this.renderer.createText(this._el_98,'\n                    ',(null as any));
    this._el_100 = this.renderer.createElement(this._el_98,'span',(null as any));
    this.renderer.setElementAttribute(this._el_100,'class','glyphicon glyphicon-trash');
    this._text_101 = this.renderer.createText(this._el_98,' Remove all\n                ',(null as any));
    this._text_102 = this.renderer.createText(this._el_78,'\n            ',(null as any));
    this._text_103 = this.renderer.createText(this._el_41,'\n\n        ',(null as any));
    this._text_104 = this.renderer.createText(this._el_12,'\n\n    ',(null as any));
    this._text_105 = this.renderer.createText(this._el_1,'\n\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_38,'change',this.eventHandler(this._handle_change_38_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._pipe_number_0 = new import13.DecimalPipe(this.parentInjector.get(import18.LOCALE_ID));
    this._map_0 = import4.pureProxy1((p0:any):{[key: string]:any} => {
      return {width: p0};
    });
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_88,'click',this.eventHandler(this._handle_click_88_0.bind(this)));
    this._expr_8 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_93,'click',this.eventHandler(this._handle_click_93_0.bind(this)));
    this._expr_10 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_98,'click',this.eventHandler(this._handle_click_98_0.bind(this)));
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._text_69,
      this._text_70,
      this._text_71,
      this._el_72,
      this._text_73,
      this._anchor_74,
      this._text_75,
      this._text_76,
      this._text_77,
      this._el_78,
      this._text_79,
      this._el_80,
      this._text_81,
      this._el_82,
      this._text_83,
      this._el_84,
      this._text_85,
      this._text_86,
      this._text_87,
      this._el_88,
      this._text_89,
      this._el_90,
      this._text_91,
      this._text_92,
      this._el_93,
      this._text_94,
      this._el_95,
      this._text_96,
      this._text_97,
      this._el_98,
      this._text_99,
      this._el_100,
      this._text_101,
      this._text_102,
      this._text_103,
      this._text_104,
      this._text_105
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import10.FileSelectDirective) && (38 === requestNodeIndex))) { return this._FileSelectDirective_38_3; }
    if (((token === import15.TemplateRef) && (74 === requestNodeIndex))) { return this._TemplateRef_74_5; }
    if (((token === import11.NgFor) && (74 === requestNodeIndex))) { return this._NgFor_74_6; }
    if (((token === import12.NgStyle) && (84 === requestNodeIndex))) { return this._NgStyle_84_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const currVal_1:any = this.context.uploader;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._FileSelectDirective_38_3.uploader = currVal_1;
      this._expr_1 = currVal_1;
    }
    changes = (null as any);
    const currVal_3:any = this.context.uploader.queue;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgFor_74_6.ngForOf = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._NgFor_74_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_74_6.ngDoCheck(); }
    const currVal_4:any = this._map_0((this.context.uploader.progress + '%'));
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgStyle_84_3.ngStyle = currVal_4;
      this._expr_4 = currVal_4;
    }
    if (!throwOnChange) { this._NgStyle_84_3.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = import4.interpolate(1,'Queue length: ',((this.context.uploader == (null as any))? (null as any): ((this.context.uploader.queue == (null as any))? (null as any): this.context.uploader.queue.length)),'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_47,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_6:boolean = !this.context.uploader.getNotUploadedItems().length;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementProperty(this._el_88,'disabled',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_8:boolean = !this.context.uploader.isUploading;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementProperty(this._el_93,'disabled',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_10:boolean = !this.context.uploader.queue.length;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementProperty(this._el_98,'disabled',currVal_10);
      this._expr_10 = currVal_10;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_change_38_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FileSelectDirective_38_3.onChange()) !== false);
    return (true && pd_0);
  }
  private _handle_click_88_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.uploader.uploadAll()) !== false);
    return (true && pd_0);
  }
  private _handle_click_93_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.uploader.cancelAll()) !== false);
    return (true && pd_0);
  }
  private _handle_click_98_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.uploader.clearQueue()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_uploadComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.uploadComponent> {
  if ((renderType_uploadComponent === (null as any))) { (renderType_uploadComponent = viewUtils.createRenderComponentType('C:/Users/chana/Desktop/Thongthan Project/07 Errors/assets/app/upload/upload.component.html',0,import8.ViewEncapsulation.Emulated,styles_uploadComponent,{})); }
  return new _View_uploadComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_uploadComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _el_3:any;
  _text_4:any;
  _text_5:any;
  _anchor_6:any;
  /*private*/ _appEl_6:import2.AppElement;
  _TemplateRef_6_5:any;
  _NgIf_6_6:import19.NgIf;
  _text_7:any;
  _anchor_8:any;
  /*private*/ _appEl_8:import2.AppElement;
  _TemplateRef_8_5:any;
  _NgIf_8_6:import19.NgIf;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _anchor_12:any;
  /*private*/ _appEl_12:import2.AppElement;
  _TemplateRef_12_5:any;
  _NgIf_12_6:import19.NgIf;
  _text_13:any;
  _anchor_14:any;
  /*private*/ _appEl_14:import2.AppElement;
  _TemplateRef_14_5:any;
  _NgIf_14_6:import19.NgIf;
  _text_15:any;
  _anchor_16:any;
  /*private*/ _appEl_16:import2.AppElement;
  _TemplateRef_16_5:any;
  _NgIf_16_6:import19.NgIf;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_9:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_uploadComponent1,renderType_uploadComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'tr',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'td',(null as any));
    this._el_3 = this.renderer.createElement(this._el_2,'strong',(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'',(null as any));
    this._text_5 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._anchor_6 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_6 = new import2.AppElement(6,0,this,this._anchor_6);
    this._TemplateRef_6_5 = new import15.TemplateRef_(this._appEl_6,viewFactory_uploadComponent2);
    this._NgIf_6_6 = new import19.NgIf(this._appEl_6.vcRef,this._TemplateRef_6_5);
    this._text_7 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._anchor_8 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_8 = new import2.AppElement(8,0,this,this._anchor_8);
    this._TemplateRef_8_5 = new import15.TemplateRef_(this._appEl_8,viewFactory_uploadComponent3);
    this._NgIf_8_6 = new import19.NgIf(this._appEl_8.vcRef,this._TemplateRef_8_5);
    this._text_9 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_0,'td',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','text-center');
    this._text_11 = this.renderer.createText(this._el_10,'\n                        ',(null as any));
    this._anchor_12 = this.renderer.createTemplateAnchor(this._el_10,(null as any));
    this._appEl_12 = new import2.AppElement(12,10,this,this._anchor_12);
    this._TemplateRef_12_5 = new import15.TemplateRef_(this._appEl_12,viewFactory_uploadComponent4);
    this._NgIf_12_6 = new import19.NgIf(this._appEl_12.vcRef,this._TemplateRef_12_5);
    this._text_13 = this.renderer.createText(this._el_10,'\n                        ',(null as any));
    this._anchor_14 = this.renderer.createTemplateAnchor(this._el_10,(null as any));
    this._appEl_14 = new import2.AppElement(14,10,this,this._anchor_14);
    this._TemplateRef_14_5 = new import15.TemplateRef_(this._appEl_14,viewFactory_uploadComponent5);
    this._NgIf_14_6 = new import19.NgIf(this._appEl_14.vcRef,this._TemplateRef_14_5);
    this._text_15 = this.renderer.createText(this._el_10,'\n                        ',(null as any));
    this._anchor_16 = this.renderer.createTemplateAnchor(this._el_10,(null as any));
    this._appEl_16 = new import2.AppElement(16,10,this,this._anchor_16);
    this._TemplateRef_16_5 = new import15.TemplateRef_(this._appEl_16,viewFactory_uploadComponent6);
    this._NgIf_16_6 = new import19.NgIf(this._appEl_16.vcRef,this._TemplateRef_16_5);
    this._text_17 = this.renderer.createText(this._el_10,'\n                    ',(null as any));
    this._text_18 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_0,'td',(null as any));
    this.renderer.setElementAttribute(this._el_19,'nowrap','');
    this._text_20 = this.renderer.createText(this._el_19,'\n                        ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_19,'button',(null as any));
    this.renderer.setElementAttribute(this._el_21,'class','btn btn-success btn-xs');
    this.renderer.setElementAttribute(this._el_21,'type','button');
    this._text_22 = this.renderer.createText(this._el_21,'\n                            ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_21,'span',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','glyphicon glyphicon-upload');
    this._text_24 = this.renderer.createText(this._el_21,' Upload\n                        ',(null as any));
    this._text_25 = this.renderer.createText(this._el_19,'\n                        ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_19,'button',(null as any));
    this.renderer.setElementAttribute(this._el_26,'class','btn btn-warning btn-xs');
    this.renderer.setElementAttribute(this._el_26,'type','button');
    this._text_27 = this.renderer.createText(this._el_26,'\n                            ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_26,'span',(null as any));
    this.renderer.setElementAttribute(this._el_28,'class','glyphicon glyphicon-ban-circle');
    this._text_29 = this.renderer.createText(this._el_26,' Cancel\n                        ',(null as any));
    this._text_30 = this.renderer.createText(this._el_19,'\n                        ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_19,'button',(null as any));
    this.renderer.setElementAttribute(this._el_31,'class','btn btn-danger btn-xs');
    this.renderer.setElementAttribute(this._el_31,'type','button');
    this._text_32 = this.renderer.createText(this._el_31,'\n                            ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_31,'span',(null as any));
    this.renderer.setElementAttribute(this._el_33,'class','glyphicon glyphicon-trash');
    this._text_34 = this.renderer.createText(this._el_31,' Remove\n                        ',(null as any));
    this._text_35 = this.renderer.createText(this._el_19,'\n                    ',(null as any));
    this._text_36 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_21,'click',this.eventHandler(this._handle_click_21_0.bind(this)));
    this._expr_9 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_26,'click',this.eventHandler(this._handle_click_26_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_31,'click',this.eventHandler(this._handle_click_31_0.bind(this)));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._anchor_6,
      this._text_7,
      this._anchor_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._anchor_12,
      this._text_13,
      this._anchor_14,
      this._text_15,
      this._anchor_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._text_36
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.TemplateRef) && (6 === requestNodeIndex))) { return this._TemplateRef_6_5; }
    if (((token === import19.NgIf) && (6 === requestNodeIndex))) { return this._NgIf_6_6; }
    if (((token === import15.TemplateRef) && (8 === requestNodeIndex))) { return this._TemplateRef_8_5; }
    if (((token === import19.NgIf) && (8 === requestNodeIndex))) { return this._NgIf_8_6; }
    if (((token === import15.TemplateRef) && (12 === requestNodeIndex))) { return this._TemplateRef_12_5; }
    if (((token === import19.NgIf) && (12 === requestNodeIndex))) { return this._NgIf_12_6; }
    if (((token === import15.TemplateRef) && (14 === requestNodeIndex))) { return this._TemplateRef_14_5; }
    if (((token === import19.NgIf) && (14 === requestNodeIndex))) { return this._NgIf_14_6; }
    if (((token === import15.TemplateRef) && (16 === requestNodeIndex))) { return this._TemplateRef_16_5; }
    if (((token === import19.NgIf) && (16 === requestNodeIndex))) { return this._NgIf_16_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = this.parent.context.uploader.isHTML5;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgIf_6_6.ngIf = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this.parent.context.uploader.isHTML5;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgIf_8_6.ngIf = currVal_2;
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this.context.$implicit.isSuccess;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgIf_12_6.ngIf = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this.context.$implicit.isCancel;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgIf_14_6.ngIf = currVal_4;
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this.context.$implicit.isError;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._NgIf_16_6.ngIf = currVal_5;
      this._expr_5 = currVal_5;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',((this.context.$implicit == (null as any))? (null as any): ((this.context.$implicit.file == (null as any))? (null as any): this.context.$implicit.file.name)),'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_4,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_7:any = ((this.context.$implicit.isReady || this.context.$implicit.isUploading) || this.context.$implicit.isSuccess);
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementProperty(this._el_21,'disabled',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_9:boolean = !this.context.$implicit.isUploading;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementProperty(this._el_26,'disabled',currVal_9);
      this._expr_9 = currVal_9;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_21_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.$implicit.upload()) !== false);
    return (true && pd_0);
  }
  private _handle_click_26_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.$implicit.cancel()) !== false);
    return (true && pd_0);
  }
  private _handle_click_31_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.$implicit.remove()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_uploadComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_uploadComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_uploadComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _pipe_number_0_0:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_uploadComponent2,renderType_uploadComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'td',(null as any));
    this.renderer.setElementAttribute(this._el_0,'nowrap','');
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._pipe_number_0_0 = import4.pureProxy2((<_View_uploadComponent0>this.parent.parent)._pipe_number_0.transform.bind((<_View_uploadComponent0>this.parent.parent)._pipe_number_0));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    this.detectContentChildrenChanges(throwOnChange);
    valUnwrapper.reset();
    const currVal_0:any = import4.interpolate(1,'',valUnwrapper.unwrap(import4.castByValue(this._pipe_number_0_0,(<_View_uploadComponent0>this.parent.parent)._pipe_number_0.transform)(((((this.parent.context.$implicit == (null as any))? (null as any): ((this.parent.context.$implicit.file == (null as any))? (null as any): this.parent.context.$implicit.file.size)) / 1024) / 1024),'.2')),' MB');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_0,currVal_0))) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_uploadComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_uploadComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_uploadComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _NgStyle_4_3:import12.NgStyle;
  _text_5:any;
  _text_6:any;
  _map_0:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_uploadComponent3,renderType_uploadComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'td',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','progress');
    this.renderer.setElementAttribute(this._el_2,'style','margin-bottom: 0;');
    this._text_3 = this.renderer.createText(this._el_2,'\n                            ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','progress-bar');
    this.renderer.setElementAttribute(this._el_4,'role','progressbar');
    this._NgStyle_4_3 = new import12.NgStyle(this.parent.parent.parentInjector.get(import17.KeyValueDiffers),new import14.ElementRef(this._el_4),this.renderer);
    this._text_5 = this.renderer.createText(this._el_2,'\n                        ',(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._map_0 = import4.pureProxy1((p0:any):{[key: string]:any} => {
      return {width: p0};
    });
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.NgStyle) && (4 === requestNodeIndex))) { return this._NgStyle_4_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this._map_0((this.parent.context.$implicit.progress + '%'));
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgStyle_4_3.ngStyle = currVal_0;
      this._expr_0 = currVal_0;
    }
    if (!throwOnChange) { this._NgStyle_4_3.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_uploadComponent3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_uploadComponent3(viewUtils,parentInjector,declarationEl);
}
class _View_uploadComponent4 extends import1.AppView<any> {
  _el_0:any;
  _el_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_uploadComponent4,renderType_uploadComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this._el_1 = this.renderer.createElement(this._el_0,'i',(null as any));
    this.renderer.setElementAttribute(this._el_1,'class','glyphicon glyphicon-ok');
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._el_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_uploadComponent4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_uploadComponent4(viewUtils,parentInjector,declarationEl);
}
class _View_uploadComponent5 extends import1.AppView<any> {
  _el_0:any;
  _el_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_uploadComponent5,renderType_uploadComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this._el_1 = this.renderer.createElement(this._el_0,'i',(null as any));
    this.renderer.setElementAttribute(this._el_1,'class','glyphicon glyphicon-ban-circle');
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._el_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_uploadComponent5(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_uploadComponent5(viewUtils,parentInjector,declarationEl);
}
class _View_uploadComponent6 extends import1.AppView<any> {
  _el_0:any;
  _el_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_uploadComponent6,renderType_uploadComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this._el_1 = this.renderer.createElement(this._el_0,'i',(null as any));
    this.renderer.setElementAttribute(this._el_1,'class','glyphicon glyphicon-remove');
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._el_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_uploadComponent6(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_uploadComponent6(viewUtils,parentInjector,declarationEl);
}